"""add_parent_id_to_devices

Revision ID: 1ead65fa554c
Revises: 176fd9e17047
Create Date: 2026-04-24 13:40:06.423879

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1ead65fa554c'
down_revision: str | None = '176fd9e17047'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'devices', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'parent_id')
    # ### end Alembic commands ###
